package dev.satotek.cellscope.data.root

import android.content.Context
import java.io.File

/**
 * Self-installs this app as a privileged system app by writing a KernelSU/Magisk module that
 * mounts our own APK into /system/priv-app plus the privapp-permissions allowlist.
 * Takes effect at the next boot; the user-installed copy in /data stays as an "update" of it.
 */
object PrivAppInstaller {
    private const val MODULE_ID = "cellscope_privapp"
    private const val MODULE_DIR = "/data/adb/modules/$MODULE_ID"

    enum class State { NOT_INSTALLED, PENDING_REBOOT, ACTIVE, PENDING_REMOVAL }

    /**
     * Fallback mount, run by ksud at post-fs-data. KernelSU (Next) 3.x delegates all `system/`
     * mounting to a "metamodule"; without one installed nothing is ever mounted. If a metamodule
     * already put us in place we do nothing. Otherwise we overlay ourselves: /data is a casefold
     * f2fs volume that overlayfs refuses as lowerdir, so the tree is staged into a tmpfs first.
     */
    private val MOUNT_SCRIPT = """
        #!/system/bin/sh
        MODDIR=${'$'}{0%/*}
        [ -f /system/priv-app/CellScope/CellScope.apk ] && exit 0
        T=/dev/$MODULE_ID
        mkdir -p "${'$'}T" || exit 0
        mount -t tmpfs -o mode=0755 tmpfs "${'$'}T" || exit 0
        cp -a "${'$'}MODDIR/system/." "${'$'}T/"
        chcon -R u:object_r:system_file:s0 "${'$'}T"
        for d in priv-app etc/permissions; do
            mount -t overlay overlay -o ro,lowerdir="${'$'}T/${'$'}d:/system/${'$'}d" "/system/${'$'}d"
            # let KernelSU/susfs hide the mount from denylisted apps, if available
            /data/adb/ksu/bin/ksu_susfs add_try_umount "/system/${'$'}d" 1 2>/dev/null
        done
        /data/adb/ksu/bin/ksu_susfs add_try_umount "${'$'}T" 1 2>/dev/null
        exit 0
    """.trimIndent()

    suspend fun state(privileged: Boolean): State {
        val r = RootShell.run("[ -d $MODULE_DIR ] && echo dir; [ -f $MODULE_DIR/remove ] && echo remove; true", 5)
        val hasDir = r.out.contains("dir"); val removing = r.out.contains("remove")
        return when {
            removing -> State.PENDING_REMOVAL
            privileged -> State.ACTIVE
            hasDir -> State.PENDING_REBOOT
            else -> State.NOT_INSTALLED
        }
    }

    /** Writes the module. Returns null on success, else the shell error. */
    suspend fun install(context: Context, versionName: String): String? {
        val pkg = context.packageName
        val apk = File(context.applicationInfo.sourceDir)
        // Stage a copy in our own cache: root can read it from there regardless of /data/app SELinux labels.
        val staged = File(context.cacheDir, "CellScope.apk")
        runCatching { apk.copyTo(staged, overwrite = true) }.getOrElse { return "copy failed: ${it.message}" }
        val script = """
            set -e
            M=$MODULE_DIR
            rm -rf "${'$'}M"
            mkdir -p "${'$'}M/system/priv-app/CellScope" "${'$'}M/system/etc/permissions"
            cat > "${'$'}M/module.prop" <<'EOP'
id=$MODULE_ID
name=CellScope priv-app
version=v$versionName
versionCode=1
author=satotek.dev
description=Mounts CellScope into /system/priv-app (READ_PRIVILEGED_PHONE_STATE). Generated by the app itself.
EOP
            cp "${staged.absolutePath}" "${'$'}M/system/priv-app/CellScope/CellScope.apk"
            cat > "${'$'}M/system/etc/permissions/privapp-permissions-cellscope.xml" <<'EOX'
<?xml version="1.0" encoding="utf-8"?>
<permissions>
    <privapp-permissions package="$pkg">
        <permission name="android.permission.READ_PRIVILEGED_PHONE_STATE"/>
        <permission name="android.permission.MODIFY_PHONE_STATE"/>
        <permission name="android.permission.READ_PRECISE_PHONE_STATE"/>
    </privapp-permissions>
</permissions>
EOX
            cat > "${'$'}M/post-fs-data.sh" <<'EOS'
$MOUNT_SCRIPT
EOS
            find "${'$'}M" -type d -exec chmod 0755 {} +
            find "${'$'}M" -type f -exec chmod 0644 {} +
            chmod 0755 "${'$'}M/post-fs-data.sh"
            chown -R 0:0 "${'$'}M"
            chcon -R u:object_r:system_file:s0 "${'$'}M/system"
            rm -f "${'$'}M/disable" "${'$'}M/remove"
            echo ok
        """.trimIndent()
        val r = RootShell.run(script, 30)
        staged.delete()
        return if (r.ok && r.out.contains("ok")) null else (r.err.ifBlank { r.out }).ifBlank { "exit ${r.exit}" }
    }

    /** Marks the module for removal at next boot (KSU/Magisk convention). */
    suspend fun uninstall(): String? {
        val r = RootShell.run("touch $MODULE_DIR/remove && echo ok", 5)
        return if (r.ok && r.out.contains("ok")) null else r.err.ifBlank { "exit ${r.exit}" }
    }

    suspend fun reboot() { RootShell.run("svc power reboot privapp || reboot", 5) }
}
